Fixed push messages for req!remove
Fixed push messages for req!remove

Initial error :

Traceback (most recent call last):
  File "geometryrequest.py", line 16319, in on_message
    msg2 = await message.channel.send(embed=embed)
  File "/usr/local/lib/python3.6/site-packages/discord/abc.py", line 891, in send
    nonce=nonce, allowed_mentions=allowed_mentions)
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.name: This field is required